from vllm import LLM, SamplingParams
from fastapi import FastAPI
from pydantic import BaseModel
import torch 

print(torch.cuda.is_available())

app = FastAPI()
llm = LLM(model="meta-llama/Llama-3.2-1B-Instruct",
          gpu_memory_utilization=0.9)  
print("Model loaded successfully.")

class QueryRequest(BaseModel):
    prompt: str
    max_tokens: int = 512
    temperature: float = 0.7
    top_p: float = 0.9

@app.post("/generate")
async def generate(request: QueryRequest):
    try:
        sampling_params = SamplingParams(
            max_tokens=request.max_tokens,
            temperature=request.temperature,
            top_p=request.top_p,
        )
        
        outputs = llm.generate(request.prompt, sampling_params)
        print("Outputs:", outputs)

        if outputs and len(outputs) > 0 and outputs[0].outputs and len(outputs[0].outputs) > 0:
            generated_text = outputs[0].outputs[0].text
            return {"response": generated_text}
        else:
            return {"response": "Error: No output generated by the model."}

    except Exception as e:
        print(f"Error in vLLM server: {e}")
        return {"response": f"Error: {e}"}
