from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from fastapi.responses import StreamingResponse
from typing import AsyncGenerator
from vllm import LLM, SamplingParams
import asyncio


app = FastAPI()

#llm = LLM(model="meta-llama/Llama-3.2-3B-Instruct",  max_model_len=7000)
llm = LLM(model="meta-llama/Llama-3.2-3B-Instruct",   
#model="meta-llama/Llama-3.1-8B-Instruct",

          max_model_len=4048,
          max_num_seqs=2) # Adjust as required)

print("Model loaded successfully.")

class QueryRequest(BaseModel):
    prompt: str
    max_tokens: int = 1028
    temperature: float = 0.3
    top_p: float = 0.8

# Async generator for streaming tokens
async def stream_tokens(llm, prompt: str, sampling_params: SamplingParams) -> AsyncGenerator[str, None]:
    try:
        # Simulate streaming tokens from the model
        async for output in llm.generate_stream(prompt, sampling_params):
            if hasattr(output, 'text'):
                yield output.text
            else:
                yield f"Unexpected output format: {output}"
    except Exception as e:
        yield f"Error during streaming: {e}"

@app.post("/generateb")
async def generateb(request: QueryRequest):
    try:
        sampling_params = SamplingParams(
            max_tokens=request.max_tokens,
            temperature=request.temperature,
            top_p=request.top_p,
            repetition_penalty=1.2  
        )
        
        outputs = llm.generate(request.prompt, sampling_params)
        print("vLLM raw outputs:", outputs)
       
        if outputs and len(outputs) > 0 and outputs[0].outputs and len(outputs[0].outputs) > 0:
            generated_text = outputs[0].outputs[0].text
            return {"response": generated_text}
        else:
            return {"response": "Error: No output generated by the model."}

    except Exception as e:
        print(f"Error in vLLM server: {e}")
        return {"response": f"Error: {e}"}

# Example usage in a FastAPI streaming route
@app.post("/generate")
async def generate(request: QueryRequest):
    try:
        sampling_params = SamplingParams(
            max_tokens=request.max_tokens,
            temperature=request.temperature,
            top_p=request.top_p,
        )

        # Generate the full output using the `generate` method
        outputs = llm.generate(request.prompt, sampling_params)
        if outputs and len(outputs) > 0 and outputs[0].outputs and len(outputs[0].outputs) > 0:
            generated_text = outputs[0].outputs[0].text

            # Simulate streaming by yielding chunks of the text
            async def event_stream():
                for i in range(0, len(generated_text), 50):  # Adjust chunk size as needed
                    chunk = generated_text[i:i+50].strip()
                    if chunk:  # Avoid streaming empty chunks
                        yield f"data: {chunk}\n\n"
                    await asyncio.sleep(0.1)

            return StreamingResponse(event_stream(), media_type="text/event-stream")
        else:
            return StreamingResponse(
                (f"data: Error: No output generated\n\n" for _ in range(1)),
                media_type="text/event-stream"
            )
    except Exception as e:
        print(f"Error in vLLM server: {e}")
        raise HTTPException(status_code=500, detail=str(e))